### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by abubelinha** [str4w/LifeAsWeeks#1]
Nice project. How can I run it?  I get this error when executing `python weeks.py`
```
  File "./weeks.py", line 57
    print ext
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(ext)?
```
Maybe I am running an old python version? (Python 3.8 under Windows 7).

Are you by chance the same strawdog3 who authored this [circular calendar](https://foulab.org/projects/strawdog/circular-calendar/)?
> The script to create the Circular Calendar can be obtained here
> [`svn co https://svn.assembla.com/svn/CircularCalendar/`](https://svn.assembla.com/svn/CircularCalendar/)
> If you decide to use it, i’d love to hear about it at strawdog3 at gmail dot com. In fact, since my documentation efforts have been minimalistic at best, i recommend that you contact me for a bit of advice about how to get going with the script.

I was very interested but I couldn't access the repository linked in there (password protected).
It would be great if you can share it in github.

Thanks a lot in advance!

**Comment by str4w** [comment]
Hi - It is not your installation, it is this CODE that is old.  It was written for python 2.   I am in fact the writer of the Circular Calendar.  Noted on both points but will take me a couple days to address.

**Comment by str4w** [comment]
Hi - it's updated and should work under python 3 now.  Please reclone though, I ended up destroying the git history for an unrelated reason.

As for the circular calendar - try this one https://observablehq.com/@str4w/circular_calendar   It's much more usable.

**Comment by abubelinha** [comment]
Thanks for the update. It works too for me now!

Thanks also for the circular calendar. I thought the original code was a Python too.
I probably found it using Google because it contained a reference to some python astronomic calculations library ... which perhaps you used at some point of the calendar creation steps?

**Comment by str4w** [comment]
Glad it works for you.

The circular calendar was a multilingual mess :-)  It did use a python lib for the astronomical calculations.  

Note that with the javascript one, the javascript astro libraries are way less accurate, arguably just wrong.  This was, in fact, one reason the project stalled.   Hopefully they are better now, but if you really care about the astronomical matters you should check them against a reliable source like the US Naval Observatory.   The python library always seemed to match up to USNO to within a minute or two at least.
